version: '3.8' ## Latest version works with Docker Engine release 18.06.0+

services:
  # Start - Core Microservices
  ## Start - Product service definition
  product:
    build: store-services/product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
      - mongodb
      - rabbitmq
    restart: on-failure
  ## End - Product service definition

  ## Start - Recommendation service definition
  recommendation:
    build: store-services/recommendation-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
      - mongodb
      - rabbitmq
    restart: on-failure
  ## End - Recommendation service definition

  ## Start - Review service definition
  review:
    build: store-services/review-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
      - mysql
      - rabbitmq
    restart: on-failure
  ## End - Review service definition

  ## Start - Store service definition
  store:
    build: store-services/store-service
    environment:
      # - SPRING_PROFILES_ACTIVE=external-OAuth-Provider
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
      - rabbitmq
    restart: on-failure
  ## End - Store service definition
  # End - Core Microservices

  # Start - Cloud Infrastructure
  ## Start - Eureka Service Discovery definition
  eureka:
    build: store-cloud-infra/eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
    restart: on-failure
  ## End - Eureka Service Discovery definition

  ## Start - Edge Server definition
  gateway:
    build: store-cloud-infra/edge-server
    ports:
      - "8443:8443"
    environment:
      # - SPRING_PROFILES_ACTIVE=external-OAuth-Provider
      - SPRING_PROFILES_ACTIVE=docker
      # dynamically change certificate at run time
      - SERVER_SSL_KEY_STORE=file:/keystore/edge.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    volumes:
      - ./config/keystore:/keystore
    depends_on:
      - config-server
      - eureka
      - auth-server
    restart: on-failure
  ## End - Edge Server definition

  ## Start - Auth Server definition
  auth-server:
    build: store-cloud-infra/authorization-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # config server credentials
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      - config-server
      - eureka
    restart: on-failure
  ## End - Auth Server definition

  ## Start - Config Server definition
  config-server:
    build: store-cloud-infra/config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - ./config/repo:/config/repo
    restart: on-failure
  ## End - Config Server definition
  # End - Cloud Infrastructure

  # Start - Data and transport Infrastructure
  ## Start - mongodb database definition
  ### $ mongo
  mongodb:
    image: mongo:4.2.6-bionic
    ports:
      - "27017-27019:27017-27019"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure
  ## End - mongodb database definition

  ## Start - MySql database definition
  ### $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:8.0.20
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  ## End - MySql database definition

  ## Start - RabbitMQ Messaging service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  ## End - RabbitMQ Messaging service

  ## Start - Zipkin Distributed Tracking visualizer
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
      - RABBIT_ADDRESSES=rabbitmq
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
    restart: on-failure
  ## Start - Zipkin Distributed Tracking visualizer
  # End - Data and transport Infrastructure
